RENAMED denoiseN4 to denoiseNLM, UPDATE arg parser, include beta and sigma for nlm

diff --git a/functions/denoiseNLM b/functions/denoiseNLM
--- a/functions/denoiseNLM
+++ b/functions/denoiseNLM
@@ -3,11 +3,13 @@ print_help() {
 echo "
 Usage:
 
-	`basename $0` NIFTI ID output_directory
+	`basename $0` <NII> <ID> <OUTDIR> [-threads N] [-sigma S] [-beta B]
 		NIFTI:		Nifti file to apply the denoise
 		ID: 		Identification for the output file (NO extension)
 		Out directory: 	Path to output, could be here '.'
-		CPUs: 		NUmber of CPU use to process the data
+		threads: 	Number of threads use to process the data, DEFAULT=6
+		sigma: 		Sigma value for NLM, DEFAULT=0 (automatic)
+		beta:		Beta value for NLM, DEFAULT=1
 
 This script aplies a non-local-means denoising using minc-toolkit and the N4 bias field correction from ANTs. 	
 NOTE: this script REQUIRES previous installation of FreeSurfer, minc-toolkit & ANTs.
@@ -23,30 +25,66 @@ BUG: in one subject the transform matrix of the denoised NIFTI changed from the 
 fslcpgeom T1.nii.gz T1_nd4.nii.gz
 
 Raul RC
-INB, January, 2018
+INB, January, 2018, Updated in June, 2026
 raulrcruces@inb.unam.mx
 
 "
 }
 
 ######### HELP ######### 
-if [ $# -lt 4 ]
-then
-	echo -e "\e[0;31m\n[ERROR]... Argument missing: \n\t\tNifti: $1\n\t\tID: $2\n\t\tOutput directory:$3 \n\t\tCPUs: $2\e[0m"
-	print_help
-	exit 1
-fi
 
 # --------------------------------------------------------------- # 
 # 		Starting Requirements & Warnings
 # --------------------------------------------------------------- # 
+
+if [ $# -lt 3 ];
+then
+	echo -e "\e[0;31m\n[ERROR]... Mandatory argument missing: \n\t\tNifti: ${1}\n\t\tID: ${2}\n\t\tOutput directory:${3}\e[0m"
+	print_help
+	exit 1
+fi
+
 NII=$1
 id=${2/.nii.gz/}
 outdir=$3
-cpus=$4
 
-echo -e "\033[48;5;22m\n[INIT]\t\tDenoise & Bias Field Correction of file $NII\n\033[0m"
-echo -e "If you use this script please remember to reference the developers:
+shift 3
+
+threads=6
+sigma=0
+beta=1
+
+while [[ $# -gt 0 ]]; do
+    case "$1" in
+        -threads)
+            threads="$2"
+            shift 2
+            ;;
+        -sigma)
+            sigma="$2"
+            shift 2
+            ;;
+        -beta)
+            beta="$2"
+            shift 2
+            ;;
+        *)
+            echo "Unknown option: $1"
+            exit 1
+            ;;
+    esac
+done
+
+echo -e "\033[38;5;45m-------------------------------------------------------------
+\t\tNLM Denoising 
+-------------------------------------------------------------\033[0m"
+echo -e "Input file:  \033[38;5;208m${NII}\033[0m"
+echo -e "Output name: \033[38;5;208m${id}\033[0m"
+echo -e "Output dir:  \033[38;5;208m${outdir}\033[0m"
+echo -e "Threads:     \033[38;5;208m${threads}\033[0m"
+echo -e "NLM sigma:   \033[38;5;208m${beta}\033[0m"
+echo -e "NLM beta:    \033[38;5;208m${sigma}\033[0m"
+echo -e "\n\nIf you use this script please remember to reference the developers:
 Tustison, N. J., Avants, B. B., Cook, P. A., Zheng, Y., Egan, A., Yushkevich, P. A., & Gee, J. C. (2010). N4ITK: improved N3 bias correction. IEEE transactions on medical imaging, 29(6), 1310-1320.  
 P. Coupé, P. Yger, S. Prima, P. Hellier, C. Kervrann, C. Barillot. An Optimized Blockwise NonLocal Means Denoising Filter for 3-D Magnetic Resonance Images. IEEE Transactions on Medical Imaging, 27(4):425–441, 2008.
 "
@@ -70,32 +108,24 @@ if [ -f $outfile ]; then echo -e "\e[0;31m\n[ERROR]... Outfile already exist: $o
 #---------------- Timer & Beginning ----------------#
 aloita=$(date +%s.%N)
 
-
 #---------------- Temporal directory ----------------# 
 mkdir $tmp
 echo  -e "\033[38;5;45m\n[INFO]... tmp directory: \033[0m"
 echo   -e "\033[38;5;208mDIR -->\t $tmp\033[0m"
-
 
 #---------------- Converts T1 nifti to minc format and back to T1  ----------------#
 echo  -e "\033[38;5;45m\n[INFO]... Creando un archivo minc \033[0m"
 mri_convert $NII ${mnc}
 
 echo  -e "\033[38;5;45m\n[INFO]... Aplicando la limpieza de ruido con non-local means \033[0m"
-mincnlm ${mnc} ${mncdn} -mt ${cpus}
+mincnlm ${mnc} ${mncdn} -mt ${threads} -sigma ${beta} -beta ${sigma}
 
 echo  -e "\033[38;5;45m\n[INFO]... Transformando de minc a nifti \033[0m"
 mri_convert ${mncdn} $outfile
 
-#echo  -e "\033[38;5;45m\n[INFO]... N4 bias field correction \033[0m"
-#N4BiasFieldCorrection -d 3 -i $out -o $outfile
-
-
-
 #----------- Removes temporal directory -----------#
 echo -e "\033[38;5;45m\n[INFO]... Removing temporal files: $tmp\e[0m"
 rm -Rv $tmp
-
 
 #----------- Outfile -----------#
 echo  -e "\033[38;5;45m\n[INFO]... Outfile: ${outfile} \033[0m"
